### PR TITLE
Fixing missing source header

### PR DESCRIPTION
**Pull request by congoamz**
### Summary

Fixing missing source header

### Description

Portions of the pgjdbc/src/main/java/software/aws/rds/jdbc/postgresql/Driver.java file came from the pgjdbc/src/main/java/org/postgresql/Driver.java file but copying the source header was missed

### Additional Reviewers

@hsuamz 
@samathaamz 
@seneramz 
@sergiyvamz 
@hyandell

### CODE REVIEW

**Comment by hyandell** [comment]
As it's an AWS file with Postgresql content copied over to it, I would go with the AWS source header first and then Postgresql. It's more stylistic than anything else, but as it's a new file that has pulled functionality over, I'd start with that "original license" (for the new file).

**Comment by congoamz** [comment]
> As it's an AWS file with Postgresql content copied over to it, I would go with the AWS source header first and then Postgresql. It's more stylistic than anything else, but as it's a new file that has pulled functionality over, I'd start with that "original license" (for the new file).

The majority of this file was actually authored by the PostgreSQL folks, there are some small bits that are Amazon-authored. Since this is the case, we've decided to keep the PostgreSQL header above the AWS one

**Comment by hyandell** [comment]
That sounds good to me then :)

**Review by hsuamz — APPROVED** [review]
LGTM.

**Pull request merged**
